const { test } = require('node:test');
const assert = require('node:assert/strict');
const { once } = require('node:events');
const { randomUUID, randomBytes } = require('node:crypto');
const { readFile, readdir } = require('node:fs/promises');
const path = require('node:path');
const bcrypt = require('bcryptjs');
const { Client } = require('pg');
const { createDatabase } = require('../../database/client');
const { createApp } = require('../../app/app');

test('real PostgreSQL: authentication, roles, sessions, records and scan persistence', { skip: !process.env.DATABASE_URL }, async (t) => {
  const schema = 'test_' + randomUUID().replaceAll('-','');
  const admin = new Client({ connectionString: process.env.DATABASE_URL });
  await admin.connect();
  await admin.query('CREATE SCHEMA ' + schema);
  const url = new URL(process.env.DATABASE_URL);
  url.searchParams.set('options', '-c search_path=' + schema);
  const db = createDatabase(url.toString());
  let server;
  t.after(async () => {
    if (server) await new Promise((resolve) => server.close(resolve));
    await db.close();
    await admin.query('DROP SCHEMA ' + schema + ' CASCADE');
    await admin.end();
  });
  const migrations = path.join(__dirname, '../../database/migrations');
  for (const name of (await readdir(migrations)).filter((name) => name.endsWith('.sql')).sort()) await db.query(await readFile(path.join(migrations, name), 'utf8'));
  const password = randomBytes(18).toString('base64url');
  for (const role of ['ADMIN','GUARD','REGISTRAR','DISCIPLINE']) await db.query('INSERT INTO users(id,username,full_name,password_hash,role) VALUES($1,$2,$3,$4,$5)', [randomUUID(), role.toLowerCase(), role, await bcrypt.hash(password,12), role]);
  const key = randomBytes(32).toString('hex');
  const config = { deviceId: 'gate-01', deviceKey: key, databaseUrl: url.toString(), appOrigins: ['http://127.0.0.1:5173'] };
  server = createApp(config,{ db, log: () => {} }).listen(0,'127.0.0.1');
  await once(server,'listening');
  let base = 'http://127.0.0.1:' + server.address().port + '/api';
  async function request(route, { method='GET', body, session, csrf=true, origin='http://127.0.0.1:5173', device=false } = {}) {
    const response = await fetch(base + route,{ method, headers: { Origin: origin, ...(body !== undefined ? { 'Content-Type': 'application/json' } : {}), ...(session ? { Cookie: session.cookie, ...(csrf ? { 'X-CSRF-Token': session.csrf } : {}) } : {}), ...(device ? { 'X-Device-Key': key } : {}) }, body: body === undefined ? undefined : JSON.stringify(body) });
    return { status: response.status, cookie: response.headers.get('set-cookie'), body: await response.json() };
  }
  async function login(username, remember=false, pass=password) {
    const result = await request('/auth/login',{ method:'POST', body:{ username, password:pass, remember } });
    assert.equal(result.status,200);
    return { cookie:result.cookie.split(';')[0], csrf:result.body.data.csrfToken, header:result.cookie, user:result.body.data.user };
  }
  assert.equal((await request('/system/status')).status,401);
  assert.equal((await request('/students')).status,401);
  assert.equal((await request('/auth/login',{method:'POST',body:{username:'admin',password:'incorrect'}})).status,401);
  assert.equal((await request('/auth/login',{method:'POST',body:{username:'admin',password},origin:'https://hostile.example'})).status,403);
  const staff = await login('admin',true);
  assert.match(staff.header,/Max-Age=604800/);
  assert.match(staff.header,/HttpOnly/);
  assert.match(staff.header,/SameSite=Strict/i);
  assert.equal((await request('/auth/me',{session:staff})).body.data.user.role,'ADMIN');
  const regular = await login('registrar');
  assert.ok(!regular.header.includes('Max-Age'));
  assert.equal((await request('/system/status',{session:regular})).status,403);
  assert.equal((await request('/system/status',{session:staff})).body.data.database.state,'connected');
  const student = {studentNo:'TEST-001',name:'Integration Student',uid:'AB010203',course:'IT',year:'1',section:'A',active:true};
  assert.equal((await request('/students',{method:'POST',body:student,session:staff,csrf:false})).status,403);
  const saved = await request('/students',{method:'POST',body:student,session:regular});
  assert.equal(saved.status,201);
  assert.equal((await request('/students',{method:'POST',body:student,session:regular})).status,409);
  const guard = await login('guard');
  assert.equal((await request('/students',{method:'POST',body:{...student,studentNo:'OTHER'},session:guard})).status,403);
  const scan = {uid:student.uid,deviceId:'gate-01',eventId:'one'};
  const accepted = await request('/entry-logs/scan',{method:'POST',body:scan,device:true});
  assert.equal(accepted.status,201); assert.equal(accepted.body.data.type,'IN');
  assert.equal((await request('/entry-logs/scan',{method:'POST',body:scan,device:true})).body.data.duplicate,true);
  assert.equal((await request('/entry-logs/scan',{method:'POST',body:{...scan,eventId:'second'},device:true})).body.data.status,'ignored');
  assert.equal((await request('/entry-logs/scan',{method:'POST',body:{...scan,uid:'FFFFFFFF'},device:true})).status,409);
  assert.equal((await request('/entry-logs/scan',{method:'POST',body:{...scan,uid:'FFFFFFFF',eventId:'unknown'},device:true})).body.data.status,'unknown');
  assert.equal(Number((await db.query('SELECT count(*) FROM entry_logs')).rows[0].count),1);
  const date = new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Manila'}).format(new Date());
  assert.equal((await request('/entry-logs?date='+date,{session:guard})).body.data.length,1);
  await request('/violations',{method:'POST',body:{studentId:saved.body.data.id,description:'Integration check'},session:guard});
  const discipline = await login('discipline');
  const violation = (await request('/violations',{session:discipline})).body.data[0];
  assert.equal((await request('/violations/'+violation.id+'/clear',{method:'PATCH',body:{},session:guard})).status,403);
  assert.equal((await request('/violations/'+violation.id+'/clear',{method:'PATCH',body:{},session:discipline})).status,200);
  assert.ok(Number((await db.query('SELECT count(*) FROM sync_outbox')).rows[0].count)>=4);
  await new Promise((resolve)=>server.close(resolve));
  server = createApp(config,{db,log:()=>{}}).listen(0,'127.0.0.1'); await once(server,'listening'); base='http://127.0.0.1:'+server.address().port+'/api';
  assert.equal((await request('/auth/me',{session:staff})).status,200,'session survives app restart');
  assert.equal((await request('/entry-logs/scan',{method:'POST',body:scan,device:true})).body.data.duplicate,true,'idempotency survives restart');
  await db.query('UPDATE sessions SET expires_at=now()-interval \'1 second\' WHERE user_id=$1',[regular.user.id]);
  assert.equal((await request('/auth/me',{session:regular})).status,401);
  await db.query('UPDATE users SET active=false WHERE id=$1',[guard.user.id]);
  assert.equal((await request('/auth/me',{session:guard})).status,401);
  assert.equal((await request('/auth/logout',{method:'POST',body:{},session:staff})).status,200);
  assert.equal((await request('/auth/me',{session:staff})).status,401);
  const beforeChange = await login('admin');
  const newPassword = randomBytes(18).toString('base64url');
  assert.equal((await request('/auth/password',{method:'POST',body:{currentPassword:password,newPassword},session:beforeChange})).status,200);
  assert.equal((await request('/auth/me',{session:beforeChange})).status,401);
  await login('admin',false,newPassword);
  assert.notEqual((await db.query("SELECT password_hash FROM users WHERE username='admin'")).rows[0].password_hash,newPassword);
});
