const { test } = require('node:test');
const assert = require('node:assert/strict');
const { randomUUID, randomBytes } = require('node:crypto');
const { once } = require('node:events');
const { readdir, readFile } = require('node:fs/promises');
const path = require('node:path');
const { Client } = require('pg');
const bcrypt = require('bcryptjs');
const sharp = require('sharp');
const { createApp } = require('../../app/app');
const { createDatabase } = require('../../database/client');

test('guard post: real photos, restricted live display, reporting, expiry and failures', { skip: !process.env.DATABASE_URL }, async (t) => {
  const schema = 'test_guard_' + randomUUID().replaceAll('-', '');
  const admin = new Client({ connectionString: process.env.DATABASE_URL });
  await admin.connect(); await admin.query('CREATE SCHEMA ' + schema);
  const url = new URL(process.env.DATABASE_URL); url.searchParams.set('options', '-c search_path=' + schema);
  const db = createDatabase(url.toString()); let server;
  t.after(async () => { if (server) await new Promise((resolve) => server.close(resolve)); await db.close(); await admin.query('DROP SCHEMA ' + schema + ' CASCADE'); await admin.end(); });
  const migrations = path.join(__dirname, '../../database/migrations');
  for (const name of (await readdir(migrations)).filter((name) => name.endsWith('.sql')).sort()) await db.query(await readFile(path.join(migrations, name), 'utf8'));
  const password = randomBytes(20).toString('hex');
  for (const role of ['ADMIN','GUARD','REGISTRAR','DISCIPLINE']) await db.query('INSERT INTO users(id,username,full_name,password_hash,role) VALUES($1,$2,$3,$4,$5)', [randomUUID(), role.toLowerCase(), role, await bcrypt.hash(password, 4), role]);
  const key = randomBytes(32).toString('hex');
  const config = { deviceId: 'gate-01', deviceKey: key, databaseUrl: url.toString(), appOrigins: ['http://127.0.0.1:5173'] };
  server = createApp(config, { db, log: () => {} }).listen(0, '127.0.0.1'); await once(server, 'listening');
  const base = 'http://127.0.0.1:' + server.address().port + '/api';
  async function request(route, method = 'GET', body, session, type) {
    const response = await fetch(base + route, { method, headers: { Origin: config.appOrigins[0], ...(body !== undefined ? { 'Content-Type': type || 'application/json' } : {}), ...(session ? { Cookie: session.cookie, 'X-CSRF-Token': session.csrf } : {}), 'X-Device-Key': key }, body: body === undefined ? undefined : type ? body : JSON.stringify(body) });
    const data = response.headers.get('content-type')?.startsWith('image/') ? Buffer.from(await response.arrayBuffer()) : await response.json();
    return { status: response.status, body: data, cookie: response.headers.get('set-cookie') };
  }
  async function login(username) { const r = await request('/auth/login', 'POST', { username, password }); assert.equal(r.status, 200); return { cookie: r.cookie.split(';')[0], csrf: r.body.data.csrfToken }; }
  const guard = await login('guard'); const registrar = await login('registrar'); const staff = await login('admin');
  assert.equal((await request('/guard/display')).status, 401);
  assert.equal((await request('/guard/dashboard', 'GET', undefined, registrar)).status, 403);
  assert.equal((await request('/guard/display', 'GET', undefined, registrar)).status, 403);
  assert.equal((await request('/guard/dashboard', 'GET', undefined, guard)).body.data.scan, null);
  const student = (await request('/students', 'POST', { studentNo: 'GUARD-TEST', name: 'Guard Test Student', course: 'IT', year: '1', uid: 'ABCDEF01' }, registrar)).body.data;
  const photo = await sharp({ create: { width: 300, height: 400, channels: 3, background: '#267154' } }).png().toBuffer();
  assert.equal((await request(`/students/${student.id}/photo`, 'PUT', photo, guard, 'image/png')).status, 403);
  assert.equal((await request(`/students/${student.id}/photo`, 'PUT', photo, { ...registrar, csrf: '' }, 'image/png')).status, 403);
  assert.equal((await request(`/students/${student.id}/photo`, 'PUT', Buffer.from('not an image'), registrar, 'image/png')).status, 422);
  assert.equal((await request(`/students/${student.id}/photo`, 'PUT', Buffer.alloc(2 * 1024 * 1024 + 1), registrar, 'image/png')).status, 413);
  assert.equal((await request(`/students/${student.id}/photo`, 'PUT', photo, registrar, 'image/png')).status, 200);
  assert.equal((await request(`/students/${student.id}/photo`)).status, 401);
  const stored = await request(`/students/${student.id}/photo`, 'GET', undefined, guard);
  assert.equal((await sharp(stored.body).metadata()).format, 'jpeg');
  assert.ok((await request('/students', 'GET', undefined, registrar)).body.data[0].photo);
  const incident = { studentId: student.id, description: 'Private incident details', requestId: randomUUID() };
  const reported = await request('/violations', 'POST', incident, guard); assert.equal(reported.status, 201);
  assert.equal((await request('/violations', 'POST', incident, guard)).status, 200);
  assert.equal((await request('/violations', 'POST', { ...incident, description: 'Changed description' }, guard)).status, 409);
  assert.equal((await request('/violations/' + reported.body.data.id + '/clear', 'PATCH', {}, guard)).status, 403);
  const scan = { uid: 'ABCDEF01', deviceId: 'gate-01', eventId: randomUUID() };
  assert.equal((await request('/entry-logs/scan', 'POST', scan)).body.data.status, 'alert');
  const dashboard = (await request('/guard/dashboard', 'GET', undefined, guard)).body.data;
  assert.equal(dashboard.scan.person.id, student.id); assert.equal(dashboard.totals.entries, 1); assert.equal(dashboard.totals.alerts, 1);
  assert.equal(dashboard.device.connection, 'online');
  const display = (await request('/guard/display', 'GET', undefined, guard)).body.data;
  assert.equal(display.scan.status, 'ok'); assert.deepEqual(Object.keys(display.scan.person).sort(), ['name','photo']);
  assert.ok(!JSON.stringify(display).includes('Private incident')); assert.ok(!JSON.stringify(display).includes('ABCDEF01'));
  const firstId = dashboard.scan.id;
  await request('/entry-logs/scan', 'POST', scan);
  assert.equal((await request('/guard/dashboard', 'GET', undefined, guard)).body.data.scan.id, firstId);
  await request('/entry-logs/scan', 'POST', { ...scan, eventId: randomUUID() });
  assert.equal((await request('/guard/display', 'GET', undefined, guard)).body.data.scan.status, 'ignored');
  await request('/entry-logs/scan', 'POST', { ...scan, uid: 'FFFFFFFF', eventId: randomUUID() });
  assert.equal((await request('/guard/display', 'GET', undefined, guard)).body.data.scan.person, null);
  await db.query('UPDATE students SET active=false WHERE id=$1', [student.id]);
  await request('/entry-logs/scan', 'POST', { ...scan, eventId: randomUUID() });
  assert.equal((await request('/guard/display', 'GET', undefined, guard)).body.data.scan.message, 'Please see the guard.');
  await db.query("UPDATE scan_events SET received_at=now()-interval '13 seconds'");
  assert.equal((await request('/guard/display', 'GET', undefined, guard)).body.data.scan, null);
  assert.equal((await request('/guard/dashboard', 'GET', undefined, guard)).body.data.totals.entries, 1);
  assert.equal((await request('/violations/' + reported.body.data.id + '/clear', 'PATCH', {}, staff)).status, 200);
  await request('/auth/logout', 'POST', {}, guard);
  assert.equal((await request('/guard/display', 'GET', undefined, guard)).status, 401);
  await db.query('ALTER TABLE scan_events RENAME TO unavailable_scan_events');
  const failure = await request('/guard/display', 'GET', undefined, staff);
  assert.equal(failure.status, 503); assert.ok(!JSON.stringify(failure.body).includes('SELECT'));
});
